# 4.1 Create Arrays

In [1]:
import numpy as np

df1 = [1,2,3,4,5]
print(df1)

[1, 2, 3, 4, 5]


In [2]:
my_arr1 = np.array(df1)

In [3]:
print(my_arr1)

[1 2 3 4 5]


In [4]:
df2 = [range(1,5), range(5,9)]

In [5]:
np.array(range(1,5))

array([1, 2, 3, 4])

In [6]:
np.array(df2)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
my_array2 = np.array(df2)

In [8]:
my_array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
my_array2.tolist() # turns into list

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [10]:
np.zeros(10) # 10 times Zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,6)) # 3 rows and 6 columns of Zero

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones(10) # 10 times One

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.linspace(0,1,5) # uniform distribution between 0 and 1 (5 times)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.logspace(0,3,4) # Returns number spaces evenly w.r.t interval on a log scale.

array([   1.,   10.,  100., 1000.])

In [15]:
inn_arr = np.arange(5)       # 5 numbers from 0 to 4 (5 is excluded)
print(inn_arr)

[0 1 2 3 4]


In [16]:
fly_arr = inn_arr.astype(float) # array of numbers which are floats
print(fly_arr)

[0. 1. 2. 3. 4.]


# 4.2  Examing Arrays

In [17]:
my_arr1.dtype # data type

dtype('int64')

In [18]:
print(my_array2.dtype)
print(my_array2)

int64
[[1 2 3 4]
 [5 6 7 8]]


In [19]:
my_array2.ndim # dimension checking

2

In [20]:
my_array2.shape # row and column checking

(2, 4)

In [21]:
my_array2.size # number of the elements or members

8

In [22]:
len(my_array2)

2

In [23]:
my_array2.tolist()

[[1, 2, 3, 4], [5, 6, 7, 8]]

# 4.3 Reshaping

In [24]:
arr1 = np.arange(10, dtype=float)
print(arr1)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [25]:
arr1 = np.arange(10, dtype=float).reshape(2,5) # reshaping to 2 rows and 5 columns
print(arr1)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [26]:
print(arr1.shape)

(2, 5)


In [27]:
print(arr1.reshape(5,2))

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [28]:
a1 = np.array([0,1])
print(a1)

[0 1]


In [29]:
a_col1 = a1[:, np.newaxis] # the newaxis is used to increase the dimension of 

                            #the existing array by one more dimension, when used once.

In [30]:
print(a_col1)

[[0]
 [1]]


In [31]:
a_col1 = a1[:None]
print(a_col1)

[0 1]


In [32]:
# Transpose
print(a_col1.T)

[0 1]


In [33]:
arr_flt1 = arr1.flatten()
print(arr_flt1)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [34]:
arr_flt1[0] = 33 # Updating the first element of the array with 33

In [35]:
print(arr_flt1)

[33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [36]:
print(arr1)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [37]:
arr_flt1 = arr1.ravel() # eturns contiguous flattened array(1D array with all the input-array elements 
                        # and with the same type as it). A copy is made only if needed
print(arr_flt1)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [38]:
arr_flt1[0] = 33

In [39]:
print(arr_flt1)

[33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [40]:
print(arr1)

[[33.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


# 4.4 Stack Arrays

In [41]:
a1 = np.array([0,1])

In [42]:
b1 = np.array([2,3])

In [43]:
ab1 = np.stack((a1,b1)).T

In [44]:
print(ab1)

[[0 2]
 [1 3]]


In [45]:
np.hstack((a1[:, None], b1[:, None]))

array([[0, 2],
       [1, 3]])

# 4.5 Selection 

In [46]:
arr1 = np.arange (10, dtype=float).reshape((2,5))

In [47]:
arr1[0]

array([0., 1., 2., 3., 4.])

In [48]:
arr1[0,3]

3.0

In [49]:
arr1[0][3]

3.0

# 4.5.1 Slicing

In [50]:
arr1[0, :]

array([0., 1., 2., 3., 4.])

In [51]:
arr1[:,0]

array([0., 5.])

In [52]:
arr1[:, :2]

array([[0., 1.],
       [5., 6.]])

In [53]:
arr1[:, 2:]

array([[2., 3., 4.],
       [7., 8., 9.]])

In [54]:
arr21 = arr1[:, 1:4]

In [55]:
print(arr21)

[[1. 2. 3.]
 [6. 7. 8.]]


In [56]:
arr21[0,0] = 33

In [57]:
print(arr21)

[[33.  2.  3.]
 [ 6.  7.  8.]]


In [58]:
print(arr1)

[[ 0. 33.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


# 4.5.2 Fancy Indexing : Integer or boolean array indexing

In [59]:
arr21 = arr1[:,[1,2,3]]

In [60]:
print(arr21)

[[33.  2.  3.]
 [ 6.  7.  8.]]


In [61]:
arr21[0,0]=44

In [62]:
print(arr21)

[[44.  2.  3.]
 [ 6.  7.  8.]]


In [63]:
print(arr1)

[[ 0. 33.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


In [64]:
arr21 = arr1[arr1 > 5]

In [65]:
print(arr21)

[33.  6.  7.  8.  9.]


In [66]:
arr21[0] = 44

In [67]:
print(arr21)

[44.  6.  7.  8.  9.]


In [68]:
print(arr1)

[[ 0. 33.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


In [69]:
# However, 

arr1[arr1 > 5]=0
print(arr1)

[[0. 0. 2. 3. 4.]
 [5. 0. 0. 0. 0.]]


In [70]:
# Bolean arrays continues

names1 = np.array(["Bob","Joe","Will","Bob"])

In [71]:
names1 =="Bob"

array([ True, False, False,  True])

In [72]:
names1[names1!="Bob"]

array(['Joe', 'Will'], dtype='<U4')

In [73]:
names1[names1 !="Bob"] = "Joe"

In [74]:
np.unique(names1)

array(['Bob', 'Joe'], dtype='<U4')

# 4.6 Vectorized Operations

In [75]:
nums1 = np.arange (5)

In [76]:
nums1*10

array([ 0, 10, 20, 30, 40])

In [77]:
nums1 = np.sqrt(nums1)

In [78]:
#np.celi(nums)
np.isnan(nums1)

array([False, False, False, False, False])

In [79]:
nums1+np.arange(5)

array([0.        , 2.        , 3.41421356, 4.73205081, 6.        ])

In [80]:
np.maximum(nums1, np.array([1,-2,3,-4,5]))

array([1.        , 1.        , 3.        , 1.73205081, 5.        ])

In [81]:
vec11 = np.random.randn(4,2)
vec21 = np.random.randn(10)
#dist = np.sqrt(np.sum((vec1-vec2)**2))

In [82]:
# Maths ans Stats
rnd1 = np.random.randn(4,2)
rnd1.mean()
rnd1.std()
rnd1.argmin()
rnd1.sum()
rnd1.sum(axis=0)
rnd1.sum(axis=1)

array([-1.78199119, -1.41948907, -1.03607639,  1.12803696])

In [83]:
# Methods for boolean arrays
(rnd1>0).sum()
(rnd1>0).any()
(rnd1>0).all()

#Random numbers
np.random.seed(12234)
np.random.rand(2,3)
np.random.randn(10)
np.random.randint(0,2,10)

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1])

# Excercises

In [84]:
X = np.random.randn(4,2)
print(X)

[[ 1.18344381 -0.44590868]
 [ 0.35305993 -0.03219138]
 [ 0.78492624  0.3056839 ]
 [-0.05014605  0.02154613]]


In [85]:
print(X[:,0].min())
print(X[:,:].min())

-0.05014604593747791
-0.44590868174241155


In [86]:
X.std()

0.4841968507743543