This is an output of Numpy package as a part of a training program       

# 4.1 Create Arrays

In [1]:
import numpy as np

df1 = [1,2,3,4,5]

In [2]:
my_arr1 = np.array(df1)

In [3]:
df2 = [range(1,5), range(5,9)]

In [4]:
my_array2 = np.array(df2)

In [5]:
my_array2.tolist()

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
np.logspace(0,3,4)

array([   1.,   10.,  100., 1000.])

In [11]:
inn_arr = np.arange(5)

In [12]:
fly_arr = inn_arr.astype(float)

# 4.2  Examing Arrays

In [13]:
my_arr1.dtype

dtype('int64')

In [14]:
my_array2.dtype

dtype('int64')

In [15]:
my_array2.ndim

2

In [16]:
my_array2.shape

(2, 4)

In [17]:
my_array2.size

8

In [18]:
len(my_array2)

2

# 4.3 Reshaping

In [19]:
arr1 = np.arange(10, dtype=float).reshape(2,5)

In [20]:
print(arr1.shape)

(2, 5)


In [21]:
print(arr1.reshape(5,2))

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [22]:
a1 = np.array([0,1])

In [23]:
a_col1 = a1[:, np.newaxis]

In [24]:
print(a_col1)

[[0]
 [1]]


In [25]:
a_col1 = a1[:None]

In [26]:
# Transpose
print(a_col1.T)

[0 1]


In [27]:
arr_flt1 = arr1.flatten()

In [28]:
arr_flt1[0] = 33

In [29]:
print(arr_flt1)

[33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [30]:
print(arr1)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [31]:
arr_flt1 = arr1.ravel()

In [32]:
arr_flt1[0] = 33

In [33]:
print(arr_flt1)

[33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [34]:
print(arr1)

[[33.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


# 4.4 Stack Arrays

In [35]:
a1 = np.array([0,1])

In [36]:
b1 = np.array([2,3])

In [37]:
ab1 = np.stack((a,b)).T

NameError: name 'a' is not defined

In [ ]:
print(ab1)

In [ ]:
np.hstack((a1[:, None], b1[:, None]))

# 4.5 Selection 

In [ ]:
arr1 = np.arange (10, dtype=float).reshape((2,5))

In [ ]:
arr1[0]

In [ ]:
arr1[0,3]

In [ ]:
arr1[0][3]

# 4.5.1 Slicing

In [ ]:
arr1[0, :]

In [ ]:
arr1[:,0]

In [ ]:
arr1[:, :2]

In [ ]:
arr1[:, 2:]

In [ ]:
arr21 = arr1[:, 1:4]

In [ ]:
print(arr21)

In [38]:
arr21[0,0] = 33

NameError: name 'arr21' is not defined

In [ ]:
print(arr21)

In [ ]:
print(arr1)

# 4.5.2 Fancy Indexing : Integer or boolean array indexing

In [ ]:
arr21 = arr1[:,[1,2,3]]

In [ ]:
print(arr21)

In [ ]:
arr21[0,0]=44

In [ ]:
print(arr21)

In [ ]:
print(arr1)

In [39]:
arr21 = arr1[arr1 > 5]

In [40]:
print(arr21)

[33.  6.  7.  8.  9.]


In [41]:
arr21[0] = 44

In [42]:
print(arr21)

[44.  6.  7.  8.  9.]


In [43]:
print(arr1)

[[33.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


In [44]:
# However, 

arr1[arr1 > 5]=0
print(arr1)

[[0. 1. 2. 3. 4.]
 [5. 0. 0. 0. 0.]]


In [45]:
# Bolean arrays continues

names1 = np.array(["Bob","Joe","Will","Bob"])

In [46]:
names1 =="Bob"

array([ True, False, False,  True])

In [47]:
names1[names1!="Bob"]

array(['Joe', 'Will'], dtype='<U4')

In [48]:
names1[names1 !="Bob"] = "Joe"

In [49]:
np.unique(names1)

array(['Bob', 'Joe'], dtype='<U4')

# 4.6 Vectorized Operations

In [50]:
nums1 = np.arange (5)

In [51]:
nums1*10

array([ 0, 10, 20, 30, 40])

In [52]:
nums1 = np.sqrt(nums1)

In [53]:
#np.celi(nums)
np.isnan(nums1)

array([False, False, False, False, False])

In [54]:
nums1+np.arange(5)

array([0.        , 2.        , 3.41421356, 4.73205081, 6.        ])

In [55]:
np.maximum(nums1, np.array([1,-2,3,-4,5]))

array([1.        , 1.        , 3.        , 1.73205081, 5.        ])

In [56]:
vec11 = np.random.randn(4,2)
vec21 = np.random.randn(10)
#dist = np.sqrt(np.sum((vec1-vec2)**2))

In [57]:
# Maths ans Stats
rnd1 = np.random.randn(4,2)
rnd1.mean()
rnd1.std()
rnd1.argmin()
rnd1.sum()
rnd1.sum(axis=0)
rnd1.sum(axis=1)

array([ 0.16240042, -0.88551346, -0.86903641, -0.31996452])

In [58]:
# Methods for boolean arrays
(rnd1>0).sum()
(rnd1>0).any()
(rnd1>0).all()

#Random numbers
np.random.seed(12234)
np.random.rand(2,3)
np.random.randn(10)
np.random.randint(0,2,10)

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1])